bck_private_space:
    path: /espace-personnel
    controller: App\Controller\BackController::privateSpace

bck_profile_management:
    path: /gestion-du-profil
    controller: App\Controller\BackController::profileManagement

bck_comfirm_obs:
    path: /gestion-du-profil
    controller: App\Controller\BackController::comfirmObs

bck_grant_naturalist:
    path: /ajouter-un-naturaliste
    controller: App\Controller\BackController::addNaturalist

