fro_mainPage:
    path: /
    controller: App\Controller\FrontController::mainPage

fro_listing:
    path: /rechercher
    controller: App\Controller\FrontController::listing

fro_birdInfo:
    path: /fiche-oiseau/{nomVerniculaire}
    controller: App\Controller\FrontController::birdInfo

fro_obsInfo:
    path: /observation/{identifiant}
    controller: App\Controller\FrontController::obsInfo

fro_observe_add:
    path: /observer
    controller: App\Controller\FrontController::observe

fro_contact:
    path: /contact
    controller: App\Controller\FrontController::contact

fro_login:
    path: /login
    controller: App\Controller\FrontController::login