#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

frontRoute:
    resource: './routes/front/routes.yaml'
    type:     yaml
    prefix:   /

backRoute:
    resource: './routes/back/routes.yaml'
    type:     yaml
    prefix:   /admin/









